---
title: "Figures and Derived Tables for Privacy of Mediated Library Services"
output: html_notebook
root.dir: "./collected data/"
---

```{r setup, include=FALSE}
require("knitr")
require(tidyr)
require(readr)
require(ggplot2)
require(dplyr)
require(magrittr)
require(janitor)
require(gplots)
opts_knit$set(root.dir = "./collected data/")
# will need tis if not using Knitr
#setwd("./collected data/") 
```
*Readability analysis*
```{r , include = FALSE}
readability.df <- read_tsv(file="Readability.tsv")
```
```{r}
readprepost.tab <- xtabs(data = readability.df, formula = `readability`~ publisher + time , subset = document=="main")
ftable(readprepost.tab)
p<-ggplot(data=subset(readability.df, document=="main" ),    aes(x=time, y=`readability`)) + geom_boxplot()
plot(p)

p<-ggplot(data=subset(readability.df, document=="main" & time == "post"),    aes(x=publisher, y=`readability`)) +
  geom_bar(stat="identity")
plot(p)

subset(readability.df,subset=document!="main" & time == "post")
```
```{r , include = FALSE}
tracking.df <- read_tsv(file="Tracking.tsv")
ntrack.df <- tracking.df %>% 
select(grep("notes",names(tracking.df),value=TRUE,invert=TRUE))
```
```{r}
tm<-as.matrix(subset(ntrack.df,time="post",select=setdiff(names(ntrack.df),c("publisher","collection","time"))))
rownames(tm)<-paste(ntrack.df$publisher,ntrack.df$collection,sep=".")
#heatmap(tm)
heatmap.2(t(tm),dendrogram="column",key=TRUE, density.info="none", trace="none",margins=c(10,15),col=rev(grey.colors(5)))
```


*EDA*
```{r}
#library(devtools1)
#devtools::install_github("joachim-gassen/ExPanDaR")
library(ExPanDaR)
ExPanD(subset(readability.df,document=="main" & time == "post"))
```
* Main Policy Analysis*
```{r , include = FALSE}
require(readxl)
policy.df <- bind_rows(sapply((1:12),function(x)read_excel("publisher_ratings.xlsx",sheet=x)))
rubric.df <- read_excel("evaluation_rubric.xlsx" , sheet = 1)
policy.df %<>% rowwise  %>% mutate(rating = mean(c(`rater:1`,`rater:2`,`rater:3`),na.rm=TRUE))
policy.df %<>% ungroup()
policy.df %<>% left_join(select(rubric.df,c("question","label","category")))
catpolicy.df <- policy.df %>% group_by(publisher,time,category) %>% summarize(catrating=mean(rating))
```
```{r}
# mean of all question scores
#policy.df %>% xtabs(rating~publisher+time,.)/length(unique(policy.df$question))

#mean of category scores
catpolicy.df %>% summarize(catmean=mean(catrating)) %>%
xtabs(catmean~publisher+time,.)

bycat.arr <- 
  catpolicy.df %>% xtabs(catrating~category+publisher+time,.)
ftable(bycat.arr)

heatmap.2(t(bycat.arr[,,1]),dendrogram="column",key=TRUE, density.info="none", trace="none",margins=c(10,15),col=rev(grey.colors(5)))

policy.df %>%  ggplot(aes(question,rating)) +geom_jitter(aes(color=time)) +facet_grid(publisher~time)

```

